// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinimalAPI_NetCore8_2024.Datos;

#nullable disable

namespace MinimalAPI_NetCore8_2024.Migrations
{
    [DbContext(typeof(ApplicationDBcontext))]
    partial class ApplicationDBcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MinimalAPI_NetCore8_2024.Modelo.Propiedad", b =>
                {
                    b.Property<int>("IdPropiedad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPropiedad"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPropiedad");

                    b.ToTable("Propiedad");

                    b.HasData(
                        new
                        {
                            IdPropiedad = 1,
                            Activa = true,
                            Descripcion = "penthouse",
                            FechaCreacion = new DateTime(2024, 2, 29, 12, 49, 34, 743, DateTimeKind.Local).AddTicks(6372),
                            Nombre = "Casa Colina campestre",
                            Ubicacion = "Bogotá"
                        },
                        new
                        {
                            IdPropiedad = 2,
                            Activa = true,
                            Descripcion = "ubicada en el sur de la ciudad",
                            FechaCreacion = new DateTime(2024, 2, 29, 12, 49, 34, 743, DateTimeKind.Local).AddTicks(6388),
                            Nombre = "Apartamento 23",
                            Ubicacion = "Bogotá"
                        },
                        new
                        {
                            IdPropiedad = 3,
                            Activa = true,
                            Descripcion = "fd",
                            FechaCreacion = new DateTime(2024, 2, 29, 12, 49, 34, 743, DateTimeKind.Local).AddTicks(6391),
                            Nombre = "Casa FAmilia Lopez",
                            Ubicacion = "Medellin"
                        },
                        new
                        {
                            IdPropiedad = 4,
                            Activa = true,
                            Descripcion = "sdfs",
                            FechaCreacion = new DateTime(2024, 2, 29, 12, 49, 34, 743, DateTimeKind.Local).AddTicks(6393),
                            Nombre = "test 23",
                            Ubicacion = "GYE"
                        },
                        new
                        {
                            IdPropiedad = 5,
                            Activa = false,
                            Descripcion = "pentdfdsfhouse",
                            FechaCreacion = new DateTime(2024, 2, 29, 12, 49, 34, 743, DateTimeKind.Local).AddTicks(6395),
                            Nombre = "casa nueva",
                            Ubicacion = "Quito"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
